# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app-container
          image: 028235673625.dkr.ecr.ap-south-1.amazonaws.com/assignment:shiv_assignment
          resources:
            limits:
              cpu: "0.5" 
              memory: "256Mi" 
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 8080
